import express from "express";
import routeHandler from "express-async-handler";
import ProductUploadController from "../../controller/admin/Product/ProductUploadController.js";
import CollectionCreateController from "../../controller/admin/Product/CollectionCreateController.js";
import OdrsController from "../../controller/admin/ords/OdrsController.js";
const route = express.Router();
route.post("/product/upload", routeHandler(ProductUploadController));
route.post("/collection/create", routeHandler(CollectionCreateController));
route.post("/order/create", routeHandler(OdrsController));
export default route;
